### ISSUE TITLE
Pruebas Funcionales

### ISSUE THREAD

**Issue by BellStare** [diegoam11/back-modulo-reclamos#10]
Asignado: @SergioCallan  @SergioCallanPerez 

Probar las funcionalidades principales del proyecto asegurándose de que cumplan con los requisitos definidos.
Probar endpoints principales de los módulos:
api_quejas.
api_reclamos.
api_solicitudes.
Usar herramientas como Postman o pytest para automatizar pruebas funcionales.
Verificar respuestas correctas (códigos HTTP, datos retornados).

**Comment by SergioCallan** [comment]
Se ha utilizado Postman y Newman para poder realizar las pruebas funcionales de las APIs. Así mismo, se generaron reportes y se integró con Jenkins para su automatización. Asimismo, se puede observar los json necesarios para cada Caso de Uso. Se adjuntan los reportes.[reportesolicitudes.pdf](https://github.com/user-attachments/files/17972109/reportesolicitudes.pdf)
[reportereclamos.pdf](https://github.com/user-attachments/files/17972111/reportereclamos.pdf)
[reportequejas.pdf](https://github.com/user-attachments/files/17972112/reportequejas.pdf)
[Pruebas funcionales- Grupo 8.pdf](https://github.com/user-attachments/files/17972110/Pruebas.funcionales-.Grupo.8.pdf)
