### ISSUE TITLE
Creacion pipeline en Jenkins

### ISSUE THREAD

**Issue by BellStare** [diegoam11/back-modulo-reclamos#12]
Asignado: @DincaAlex 

Configurar un pipeline en Jenkins para ejecutar pruebas automatizadas en cada commit.

Tareas:
-Crear un pipeline para pruebas unitarias, estáticas y funcionales.
-Integrar Jenkins con SonarQube.
-Garantizar que el pipeline se ejecute automáticamente con cada push.

**Comment by DincaAlex** [comment]
Se creo un pipeline en Jenkins con las siguientes etapas:
- Deployment (Django)
- Pruebas Estaticas (SonarQube)
- Pruebas Unitarias (Pytests)
- Pruebas Funcionales (Postman/Newman)
- Pruebas de Seguridad (OWASP ZAP)
- Pruebas de Rendimiento (Locust)
El script se puede encontrar en la rama principal bajo el archivo [pipeline_script.txt](https://github.com/diegoam11/back-modulo-reclamos/blob/main/pipeline_script.txt) y las instrucciones en el [Readme.md](https://github.com/diegoam11/back-modulo-reclamos/blob/main/README.md). @
