### ISSUE TITLE
Modo DEBUG esta habilitado en core/settings.py

### ISSUE THREAD

**Issue by DincaAlex** [diegoam11/back-modulo-reclamos#15]
https://github.com/diegoam11/back-modulo-reclamos/blob/104da50d81be20b9a90c5a0ea3aedeebec934b9d/core/settings.py#L19

Deshabilitar el modo debug.

**Comment by OscarILS** [comment]
Se ha deshabilitado el modo debug 
`# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False`

**Comment by DincaAlex** [comment]
Issue resuelto en el commit 9239bee405a9f8a8bf37876ad49bcb5daf0e0eb1 .
