### ISSUE TITLE
Codigo comentado en api_reclamos/models.py

### ISSUE THREAD

**Issue by DincaAlex** [diegoam11/back-modulo-reclamos#16]
https://github.com/diegoam11/back-modulo-reclamos/blob/104da50d81be20b9a90c5a0ea3aedeebec934b9d/api_reclamos/models.py#L3

Averiguar si se puede eliminar este código comentado.

**Comment by BellStare** [comment]
Se puede proceder con borrar el comentario, dado que:

- En el código no se hace ninguna referencia al códiggo ResponseStrategy
- Tampoco tiene efecto funcional.

**Comment by BellStare** [comment]
Se procedió con la eliminación de la línea comentada.

**Comment by DincaAlex** [comment]
Issue resuelto en el commit 69b729df78cbeb1341a316fee185089c722a21c5.
