### ISSUE TITLE
Pruebas Funcionales

### ISSUE THREAD

**Issue by BellStare** [diegoam11/back-modulo-reclamos#3]
Asignado: @SergioCallan 

- Probar las funcionalidades principales del proyecto asegurándose de que cumplan con los requisitos definidos.
- Probar endpoints principales de los módulos:
         api_quejas.
         api_reclamos.
         api_solicitudes.
- Usar herramientas como Postman o pytest para automatizar pruebas funcionales.
- Verificar respuestas correctas (códigos HTTP, datos retornados).

**Comment by SergioCallan** [comment]
[Pruebas funcionales- Grupo 8.pdf](https://github.com/user-attachments/files/17969838/Pruebas.funcionales-.Grupo.8.pdf)
[reportesolicitudes.pdf](https://github.com/user-attachments/files/17969845/reportesolicitudes.pdf)
[reportereclamos.pdf](https://github.com/user-attachments/files/17969846/reportereclamos.pdf)
[reportequejas.pdf](https://github.com/user-attachments/files/17969847/reportequejas.pdf)
Se ha utilizado Postman para realizar las pruebas funcionales y Newman para poder generar los reportes adjuntados. Asimismo, se adjunta los casos de uso en un documento que ha sido la base de la utilización de las requests de las APIs.

**Comment by SergioCallan** [comment]
También se ha añadido al github para una mejor visibilidad.
