### ISSUE TITLE
Pruebas de Seguridad

### ISSUE THREAD

**Issue by BellStare** [diegoam11/back-modulo-reclamos#4]
Asignado: @OscarILS 
Evaluar la seguridad del sistema, enfocándose en la protección de datos y vulnerabilidades en los endpoints.

- Usar OWASP ZAP para analizar endpoints principales
     - Probar contra vulnerabilidades comunes:
         -SQL Injection.
         -XSS.
         -Broken Authentication.
- Generar un informe con los hallazgos y correcciones sugeridas.

**Comment by OscarILS** [comment]
Hola,
He completado la evaluación de los endpoints utilizando OWASP ZAP. A continuación presento el informe detallado con todos los hallazgos y las recomendaciones específicas se encuentra adjunto para su revisión. Quedo atento a cualquier comentario o consulta.

[Informe de vulnerabilidades web-backend.pdf](https://github.com/user-attachments/files/17970304/Informe.de.vulnerabilidades.web-backend.pdf)

Gracias,
OscarILS
