### ISSUE TITLE
Pruebas Estáticas

### ISSUE THREAD

**Issue by BellStare** [diegoam11/back-modulo-reclamos#8]
Asignado: @DincaAlex

Configurar y ejecutar análisis de código con SonarQube
Revisar los resultados de análisis para:
- Corregir problemas críticos (bugs, vulnerabilidades).
- Mejorar el cumplimiento de estándares de calidad.
Asegurar que todo el código del proyecto pase las métricas configuradas en SonarQube (como cobertura, duplicación, etc.).

**Comment by DincaAlex** [comment]
Se configuró SonarQube para el análisis estático del proyecto.
El primer [reporte](https://imgur.com/a/uZLUp9H) muestra solo 2 bugs. Se ignoraron varios bugs falsos positivos en los siguientes archivos:
- back-modulo-reclamos/postman/reportequejas.html
- back-modulo-reclamos/postman/postman/reportereclamos.html
- back-modulo-reclamos/postman/postman/reportesolicitudes.html
