### ISSUE TITLE
Pruebas Unitarias

### ISSUE THREAD

**Issue by BellStare** [diegoam11/back-modulo-reclamos#9]
Asignado: @diegoam11

Implementar pruebas unitarias en los siguientes módulos:
api_quejas (tests para modelos, vistas y serializadores).
api_reclamos (tests para modelos, vistas y serializadores).
api_solicitudes (tests para modelos, vistas y serializadores).

**Comment by diegoam11** [comment]
Buenas noches, se llevaron a cabo las pruebas unitarias conforme a los criterios previamente establecidos. La implementación se encuentra en la carpeta tests, en la raíz del proyecto.
